### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by MrNannings** [SethRobertson/GitBestPractices#15]
in the paragraph, Do backups
" though see also discussions about custom backup techniques to ensure git consistency. "

this link: http://thread.gmane.org/gmane.comp.version-control.git/168699 is not working.

shows only "ArchivedAt Nothing found - bye"

**Comment by SethRobertson** [comment]
Thanks fixed with http://marc.info/?l=git&m=136422341014631&w=2
Note I also put some text in promoting `git bundle create ... --all` as a method to create consistent backups.
