### ISSUE TITLE
readme hyperlink not secure

### ISSUE THREAD

**Issue by kevinbolger** [SethRobertson/GitBestPractices#17]
I found your website through google and it brought me to (https://sethrobertson.github.io/GitBestPractices/).

However, when I followed that article to this repo, I re navigated to the website via the url in the README.md file. The hyperlinks within link to (http://sethrobertson.github.com/GitBestPractices/) which gives a Not Secure message in the search bar on most browsers.

**Comment by woctezuma** [comment]
I get error 404 instead.

**Comment by SethRobertson** [comment]
Fixed, after only two years.  Thanks to woctezuma for reminding me (on a holiday weekend so I had some spare time).
